public class Sampan extends TransportasiAir {
    protected boolean layar;
    
    public Sampan(String informasi, String berlayar, String berlabuh) {
      super (jumlahKursi, biaya, layar);
      this.layar = ;
    }
  
    
    public void informasi() {
      if (layar == true) {
      System.out.println("Transportasi jenis Sampan dengan kursi berjumlah " + jumlahKursi + " dengan ram sebesar " + ram + " GB dan processor secepat " + processor + " Ghz. Selain itu, laptop ini memiliki webcam");
      } else {   
    }
  }
  