public class TransportasiAir {
    protected String informasi;
    protected int berlayar;
    protected double berlabuh;
    
    public Perangkat(String informasi, int berlayar, Double berlabuh) {
      this.informasi = informasi;
      this.berlayar = berlayar;
      this.informasi = informasi;
    }
  
    public void informasi() {
      System.out.println();
      System.out.println();
    }
  }